### ISSUE TITLE
topic是固定死的一个值，该如何配置呢？

### ISSUE THREAD

**Issue by myokok** [hayrullahcansu/nlog-kafka-target#1]
topic是固定死的一个值，该如何配置呢？

**Comment by hayrullahcansu** [comment]
@myokok, i don't understand you, can you please explain the issue in English?

**Comment by myokok** [comment]
Topic is a fixed value, how to configure it?

**Comment by myokok** [comment]
in  your nlog.config,topic used the style of Layout.
 but  my  project    only have one topic  to connect the kafka ,how to configure the topic ?

**Comment by hayrullahcansu** [comment]
@myokok You just put the text for topic what you want.
You can set `topic="bigbiglog"`, that way will produce logs to a static topic.
