### ISSUE TITLE
Expanding more configuration options

### ISSUE THREAD

**Issue by thinking-and-coding** [hayrullahcansu/nlog-kafka-target#16]
**Describe the bug**
When using a higher version of Confluent.Kafka like 2.x, an SSL exception will occur if "SslEndpointIdentificationAlgorithm" configuration is not set. I found that in the new version, the default parameter of this configuration item has been changed by the official[Notable changes in 2.0.0](https://kafka.apache.org/documentation/#upgrade_200_notable).So,can we support expanding more configuration options or support it in some way?

**Error message**
SSL handshake failed: error:0A000086:SSL routines::certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed

**Comment by snakefoot** [comment]
Created  #17 where you can configure:
```xml
<setting key="ssl.endpoint.identification.algorithm" value="https" />
```
Though with Confluent.Kafka ver. 2, then the default value have automatically changed to `https`, so setting is actually not needed. Unless wanting empty value=""

**Comment by hayrullahcansu** [comment]
@thinking-and-coding @snakefoot thank you for the collaboration & fix. 

new version (2.1.7) is available https://www.nuget.org/packages/NLog.Targets.KafkaAppender/2.1.7
