### ISSUE TITLE
Cannot connect to kafka on localhost:9092

### ISSUE THREAD

**Issue by IrinaFikh** [hayrullahcansu/nlog-kafka-target#5]
Can you please provide working example with configuration in code and json layout ?
I receive messages that brokers are down ...

Target settings:
var target = new KafkaAppender();
target.Name = "kafka";
target.Brokers = "localhost:9092";
target.Topic = "test";
target.Async = true;
target.Layout = new JsonLayout();
target.Debug = true;

With Confluent.Kafka I can work on same brokers/topic. 

There I see only next:
%3|1635404876.657|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Unknown error (after 2017ms in state CONNECT)

Thanks!

**Comment by hayrullahcansu** [comment]
Hi @IrinaFikh,

can you please tell me the following details?

dotnet version:
Kafka version:
Confluent.Kafka version:

**Comment by irafikh** [comment]
Sorry, not actual for me already.
Anyway what I know about env - .net 4.6, kafka from image: confluentinc/cp-kafka:latest, and latest on question time Confluent.Kafka.

**Comment by hayrullahcansu** [comment]
I see that let me test it with docker.
