### ISSUE TITLE
Kafka not accessible - app processing is ruined 

### ISSUE THREAD

**Issue by Coleman0701** [hayrullahcansu/nlog-kafka-target#6]
Hi,
we have integrated your Kafka appender nuget into couple of our applications. We send logs to Kafka, then push them to Elastic Search. 
I've tested scenarios when Kafka is not accessible. Either Kafka service is stopped or the VM hosting Kafka is shut down.

This scenario ruins the application using nlog with Kafka target. The processing of the application doesn't start since Kafka is not accessible. 
Is it somehow possible to configure it? I mean, if Kafka is not accessible, application can run properly? I have tried async mode and it doesn't help. 
Thank you for your help

**Comment by hayrullahcansu** [comment]
Hi @Coleman0701 

Have you tried to configure fallback-group?
https://github.com/nlog/NLog/wiki/FallbackGroup-target

If it doesn't help, just let me know.
